/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestordearchivos;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MBanegas
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        jm_registro.setForeground(Color.GRAY);
        jm_estandarizacion.setForeground(Color.gray);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_Campos = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jb_agregarcampo = new javax.swing.JButton();
        jb_modificarcampo = new javax.swing.JButton();
        jb_listarcampo = new javax.swing.JButton();
        jb_borrarcampo = new javax.swing.JButton();
        jb_regresarcampos = new javax.swing.JButton();
        jd_Registro = new javax.swing.JDialog();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jd_Estandarizacion = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jb_cargararchivo = new javax.swing.JButton();
        jb_nuevoarchivo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jm_archivo = new javax.swing.JMenu();
        jm_campos = new javax.swing.JMenuItem();
        jm_registro = new javax.swing.JMenuItem();
        jm_estandarizacion = new javax.swing.JMenuItem();
        jm_guardar = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        jd_Campos.setSize(new java.awt.Dimension(700, 700));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("GESTOR DE BASES DE DATOS OVAC");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Menu Campos");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo", "Tamaño", "Llave Unica"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jb_agregarcampo.setText("Agregar Campo");
        jb_agregarcampo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarcampoMouseClicked(evt);
            }
        });

        jb_modificarcampo.setText("Modificar Campos");
        jb_modificarcampo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_modificarcampoMouseClicked(evt);
            }
        });

        jb_listarcampo.setText("Listar Campos");
        jb_listarcampo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_listarcampoMouseClicked(evt);
            }
        });

        jb_borrarcampo.setText("Borrar Campos");
        jb_borrarcampo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_borrarcampoMouseClicked(evt);
            }
        });

        jb_regresarcampos.setText("Regresar");
        jb_regresarcampos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_regresarcamposMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_CamposLayout = new javax.swing.GroupLayout(jd_Campos.getContentPane());
        jd_Campos.getContentPane().setLayout(jd_CamposLayout);
        jd_CamposLayout.setHorizontalGroup(
            jd_CamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
            .addGroup(jd_CamposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118)
                .addGroup(jd_CamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_regresarcampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_modificarcampo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_agregarcampo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_listarcampo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_borrarcampo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_CamposLayout.setVerticalGroup(
            jd_CamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CamposLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jd_CamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jd_CamposLayout.createSequentialGroup()
                        .addComponent(jb_agregarcampo)
                        .addGap(18, 18, 18)
                        .addComponent(jb_modificarcampo)
                        .addGap(18, 18, 18)
                        .addComponent(jb_listarcampo)
                        .addGap(18, 18, 18)
                        .addComponent(jb_borrarcampo)))
                .addGap(18, 18, 18)
                .addComponent(jb_regresarcampos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jd_Registro.setSize(new java.awt.Dimension(700, 700));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 695, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Agregar", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 695, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Listar", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 695, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Buscar", jPanel6);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 695, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Modificar", jPanel7);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 695, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Borrar", jPanel8);

        javax.swing.GroupLayout jd_RegistroLayout = new javax.swing.GroupLayout(jd_Registro.getContentPane());
        jd_Registro.getContentPane().setLayout(jd_RegistroLayout);
        jd_RegistroLayout.setHorizontalGroup(
            jd_RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jd_RegistroLayout.setVerticalGroup(
            jd_RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        jd_Estandarizacion.setSize(new java.awt.Dimension(700, 700));

        jLabel3.setText("Estandarizacion");

        jButton11.setText("Excel");

        jButton12.setText("XLM");

        javax.swing.GroupLayout jd_EstandarizacionLayout = new javax.swing.GroupLayout(jd_Estandarizacion.getContentPane());
        jd_Estandarizacion.getContentPane().setLayout(jd_EstandarizacionLayout);
        jd_EstandarizacionLayout.setHorizontalGroup(
            jd_EstandarizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_EstandarizacionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton11)
                .addGap(239, 239, 239))
            .addGroup(jd_EstandarizacionLayout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addGroup(jd_EstandarizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton12)
                    .addComponent(jLabel3))
                .addContainerGap(315, Short.MAX_VALUE))
        );
        jd_EstandarizacionLayout.setVerticalGroup(
            jd_EstandarizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_EstandarizacionLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel3)
                .addGap(196, 196, 196)
                .addComponent(jButton11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addComponent(jButton12)
                .addGap(258, 258, 258))
        );

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("GESTOR DE BASES DE DATOS OVAC");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jb_cargararchivo.setText("Cargar Archivos");
        jb_cargararchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_cargararchivoMouseClicked(evt);
            }
        });

        jb_nuevoarchivo.setText("Nuevo Archivo");
        jb_nuevoarchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_nuevoarchivoMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GESTOR DE BASES DE DATOS OVAC");

        jm_archivo.setText("Archivo");
        jm_archivo.setEnabled(false);
        jm_archivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jm_archivoMouseClicked(evt);
            }
        });

        jm_campos.setText("Campos");
        jm_campos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_camposActionPerformed(evt);
            }
        });
        jm_archivo.add(jm_campos);

        jm_registro.setText("Registros");
        jm_registro.setEnabled(false);
        jm_registro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jm_registroMouseClicked(evt);
            }
        });
        jm_archivo.add(jm_registro);

        jm_estandarizacion.setText("Estandarizacion");
        jm_estandarizacion.setEnabled(false);
        jm_archivo.add(jm_estandarizacion);

        jMenuBar1.add(jm_archivo);

        jm_guardar.setText("Guardar Archivo");
        jm_guardar.setEnabled(false);
        jm_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jm_guardarMouseClicked(evt);
            }
        });
        jm_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_guardarActionPerformed(evt);
            }
        });
        jMenuBar1.add(jm_guardar);

        jMenu3.setText("Exit");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jb_cargararchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jb_nuevoarchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_cargararchivo)
                .addGap(73, 73, 73)
                .addComponent(jb_nuevoarchivo)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        try {
            // TODO add your handling code here:
            if (flujo != null) {
                flujo.close();
            }
        } catch (IOException ex) {
        }
        System.exit(0);
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jb_cargararchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_cargararchivoMouseClicked
        JFileChooser jf = new JFileChooser();

        try {
            FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos OVAC", "ovac");
            //FileNameExtensionFilter filtro2 = new FileNameExtensionFilter("Imagenes", "jpg", "png", "bmp");
            jf.setFileFilter(filtro);
            //jf.addChoosableFileFilter(filtro2);
            int selec = jf.showOpenDialog(this);
            
            if (selec == JFileChooser.APPROVE_OPTION) {
                archivo=jf.getSelectedFile();
                flujo=new RandomAccessFile(archivo, "rw");
                try {
                    for (int i = 0; i < 8; i++) {
                        campos.add(flujo.readUTF());
                        tiposcampos.add(flujo.readUTF());
                        sizecampos.add(flujo.readInt());
                        llaveunica.add(flujo.readBoolean());
                    }
                } catch (Exception e) {
                    System.err.println(e.getMessage());
                    System.out.println("Campos= "+campos.size());
                    System.out.println("Tipos= "+tiposcampos.size());
                    System.out.println("Tamaños= "+sizecampos.size());
                    System.out.println("Llaves= "+llaveunica.size());
                }
                JOptionPane.showMessageDialog(this, "Archivo Cargado Exitosamente");

                // despues de que cargue el archivo valido
                jm_archivo.setEnabled(true);
                jb_nuevoarchivo.setEnabled(false);

            } else {
                JOptionPane.showMessageDialog(this, "No Cargo Ningun Archivo");
            }

        } catch (Exception e) {
            System.err.println(e.getMessage());
        }

    }//GEN-LAST:event_jb_cargararchivoMouseClicked

    private void jb_nuevoarchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_nuevoarchivoMouseClicked
        if (jb_nuevoarchivo.isEnabled() == true) {
            String path = JOptionPane.showInputDialog("Ingrese el nombre del archivo: \n***Asegurese de que no existe un archivo con el mismo nombre***");
            archivo = new File("./" + path + ".ovac");
            while (archivo.exists()) {
                path = JOptionPane.showInputDialog("Ingrese el nombre del archivo: \n***Asegurese de que no existe un archivo con el mismo nombre***");
                archivo = new File("./" + path + ".ovac");
            }
            try {
                archivo.createNewFile();
                flujo = new RandomAccessFile(archivo, "rw");
            } catch (Exception e) {
                System.err.println(e.getMessage());
            }
            //despues de crear un archivo enable para guardarlo y enable para archivo
            jb_nuevoarchivo.setEnabled(false);
            jm_archivo.setEnabled(true);
            jm_guardar.setEnabled(true);
        }
    }//GEN-LAST:event_jb_nuevoarchivoMouseClicked

    private void jm_archivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jm_archivoMouseClicked

        //luego de crear un campo enable agregar a registro y estandarizacion
        jm_registro.setEnabled(true);
        jm_estandarizacion.setEnabled(true);
    }//GEN-LAST:event_jm_archivoMouseClicked

    private void jm_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jm_guardarMouseClicked
        if (jm_guardar.isEnabled()==true) {
            try {
                for (int i = 0; i < campos.size(); i++) {
                    flujo.writeUTF(campos.get(i));
                    flujo.writeUTF(tiposcampos.get(i));
                    flujo.writeInt(sizecampos.get(i));
                    flujo.writeBoolean(llaveunica.get(i));
                }

                flujo.close();
            } catch (IOException ex) {
                System.out.println(ex.getMessage());
            }
            campos.clear();
            sizecampos.clear();
            llaveunica.clear();
            tiposcampos.clear();
            jm_archivo.setEnabled(false);
            jm_guardar.setEnabled(false);
            jb_cargararchivo.setEnabled(true);
            jb_nuevoarchivo.setEnabled(true);
        }
    }//GEN-LAST:event_jm_guardarMouseClicked

    private void jb_agregarcampoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarcampoMouseClicked
        // TODO add your handling code here:
        if (campos.size() < 8) {
            String campo;
            do {
                campo = JOptionPane.showInputDialog("Ingrese el nombre del campo:\n*Menor o igual a 12 caracteres*");
            } while (campo == null || campo.equals("") || campo.length() > 12);
            String[] tipos = {"int", "String", "double", "boolean"};
            int respuesta = JOptionPane.showOptionDialog(null, "Presione el boton del tipo de dato a usar en el campo:",
                    "Seleccione un tipo", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, tipos, tipos[0]);
            String tipo = "";
            switch (respuesta) {
                case 0:
                    tipo = "int";
                    break;
                case 1:
                    tipo = "String";
                    break;
                case 2:
                    tipo = "double";
                    break;
                case 3:
                    tipo = "boolean";
                default:
                    break;
            }
            int size = -1;
            while (size < 1 || size > 15) {
                try {
                    if (tipo.equals("int")||tipo.equals("double")) {
                        
                    }else{
                        size = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el tamaño del campo entre 1-15:"));
                    }
                } catch (Exception e) {
                    size = -1;
                }
            }
            boolean flag=false;
            for (int i = 0; i < llaveunica.size(); i++) {
                if (llaveunica.get(i)==true) {
                    flag=true;
                }
            }
            if (flag) {
                //Valida que la llave sea unica
            }else{
                int confirmacion = JOptionPane.showConfirmDialog(null, "El campo es una llave?", null, JOptionPane.YES_NO_OPTION);
                if (confirmacion == JOptionPane.YES_OPTION) {
                    llaveunica.add(true);
                } else if (confirmacion == JOptionPane.NO_OPTION) {
                    llaveunica.add(false);
                    System.out.println("Entra");
                }
            }            
            campos.add(campo);
            tiposcampos.add(tipo);
            sizecampos.add(size);
            JOptionPane.showMessageDialog(this, "Se ha agregado el campo exitosamente.");

            jm_registro.setForeground(Color.BLACK);
            jm_estandarizacion.setForeground(Color.BLACK);

            jm_registro.setEnabled(true);
            jm_estandarizacion.setEnabled(true);

        }
    }//GEN-LAST:event_jb_agregarcampoMouseClicked

    private void jb_modificarcampoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_modificarcampoMouseClicked
        // TODO add your handling code here:
        if (campos.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay campos creados.");
        } else {
            String menu = "";
            for (int i = 0; i < campos.size(); i++) {
                menu += "Posicion:" + i + " " + campos.get(i) + "\n";
            }
            int opc = -1;
            while (opc < 0 || opc > campos.size()) {
                try {
                    opc = Integer.parseInt(JOptionPane.showInputDialog("Menu\n" + menu + "Ingrese la posicion de campo a modificar:"));
                } catch (Exception e) {
                    opc = -1;
                }
            }
            String campo;
            do {
                campo = JOptionPane.showInputDialog("Ingrese el nombre del campo:\n*Menor o igual a 12 caracteres*");
            } while (campo == null || campo.equals("") || campo.length() > 12);
            String[] tipos = {"int", "String", "double", "boolean"};
            int respuesta = JOptionPane.showOptionDialog(null, "Presione el boton del tipo de dato a usar en el campo:",
                    "Seleccione un tipo", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, tipos, tipos[0]);
            String tipo = "";
            switch (respuesta) {
                case 0:
                    tipo = "int";
                    break;
                case 1:
                    tipo = "String";
                    break;
                case 2:
                    tipo = "double";
                    break;
                case 3:
                    tipo = "boolean";
                default:
                    break;
            }
            int size = -1;
            while (size < 1 || size > 15) {
                try {
                    if (tipo.equals("int")||tipo.equals("double")) {
                        
                    }else{
                        size = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el tamaño del campo entre 1-15:"));
                    }                 
                } catch (Exception e) {
                    size = -1;
                }
            }
            boolean flag=false;
            for (int i = 0; i < llaveunica.size(); i++) {
                if (llaveunica.get(i)==true) {
                    flag=true;
                }
            }
            if (flag) {
                //Valida que la llave sea unica
            }else{
                int confirmacion = JOptionPane.showConfirmDialog(null, "El campo es una llave?", null, JOptionPane.YES_NO_OPTION);
                if (confirmacion == JOptionPane.YES_OPTION) {
                    llaveunica.remove(opc);
                    llaveunica.add(opc, true);
                } else if (confirmacion == JOptionPane.NO_OPTION) {
                    llaveunica.remove(opc);
                    llaveunica.add(opc, false);
                    System.out.println("Entra Modificar");
                }
            }
            campos.remove(opc);
            campos.add(opc, campo);
            tiposcampos.remove(opc);
            tiposcampos.add(opc, tipo);
            sizecampos.remove(opc);
            sizecampos.add(opc, size);
            JOptionPane.showMessageDialog(this, "Se ha modificado el campo exitosamente.");
        }
    }//GEN-LAST:event_jb_modificarcampoMouseClicked

    private void jb_listarcampoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_listarcampoMouseClicked
        // TODO add your handling code here:
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Nombre", "Tipo", "Tamaño", "Llave Unica"
                }
        ));
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        for (int i = 0; i < campos.size(); i++) {
            if (sizecampos.get(i)!=-1) {
                Object[] row = {campos.get(i), tiposcampos.get(i), sizecampos.get(i), llaveunica.get(i)};
                modelo.addRow(row);
            }else{
                Object[] row = {campos.get(i), tiposcampos.get(i), "N/A", llaveunica.get(i)};
                modelo.addRow(row);
            }           
        }
        jTable1.setModel(modelo);
        JOptionPane.showMessageDialog(this, "Se ha completado la lista de campos.");
    }//GEN-LAST:event_jb_listarcampoMouseClicked

    private void jb_borrarcampoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_borrarcampoMouseClicked
        // TODO add your handling code here:
        if (campos.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay campos creados.");
        } else {
            String menu = "";
            for (int i = 0; i < campos.size(); i++) {
                menu += "Posicion:" + i + " " + campos.get(i) + "\n";
            }
            int opc = -1;
            while (opc < 0 || opc > campos.size()) {
                try {
                    opc = Integer.parseInt(JOptionPane.showInputDialog("Menu\n" + menu + "Ingrese la posicion de campo a borrar:"));
                } catch (Exception e) {
                    opc = -1;
                }
            }
            campos.remove(opc);
            sizecampos.remove(opc);
            llaveunica.remove(opc);
            tiposcampos.remove(opc);
            JOptionPane.showMessageDialog(this, "Se ha borrado el campo exitosamente.");
        }
    }//GEN-LAST:event_jb_borrarcampoMouseClicked

    private void jb_regresarcamposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_regresarcamposMouseClicked
        // TODO add your handling code here:
        boolean flag=false;
        for (int i = 0; i < llaveunica.size(); i++) {
            if (llaveunica.get(i)==true) {
                flag=true;
                break;
            }
        }
        if (flag) {
            jd_Campos.dispose();
        }else{
            JOptionPane.showMessageDialog(jd_Campos, "Debe tener al menos un campo que sea llave!\nIntente de nuevo luego de crear un campo llave\nSi llego al maximo de campos se recomienda borrar o modificar un campo!");
        }
    }//GEN-LAST:event_jb_regresarcamposMouseClicked

    private void jm_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_guardarActionPerformed
        // TODO add your handling code here:
        try {
            //Metadata size 400
            for (int i = 0; i < campos.size(); i++) {
                flujo.writeUTF(campos.get(i));
                flujo.writeUTF(tiposcampos.get(i));
                flujo.writeInt(sizecampos.get(i));
                flujo.writeBoolean(llaveunica.get(i));
            }
            

            flujo.close();
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
        jm_archivo.setEnabled(false);
        jm_guardar.setEnabled(false);
        jb_nuevoarchivo.setEnabled(true);
    }//GEN-LAST:event_jm_guardarActionPerformed

    private void jm_registroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jm_registroMouseClicked
        jd_Registro.setModal(true);
        jd_Registro.pack();
        jd_Registro.setLocationRelativeTo(this);
        jd_Registro.setVisible(true);
    }//GEN-LAST:event_jm_registroMouseClicked

    private void jm_camposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_camposActionPerformed
        // TODO add your handling code here:
        jd_Campos.setModal(true);
        jd_Campos.pack();
        jd_Campos.setLocationRelativeTo(this);
        jd_Campos.setVisible(true);
    }//GEN-LAST:event_jm_camposActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jb_agregarcampo;
    private javax.swing.JButton jb_borrarcampo;
    private javax.swing.JButton jb_cargararchivo;
    private javax.swing.JButton jb_listarcampo;
    private javax.swing.JButton jb_modificarcampo;
    private javax.swing.JButton jb_nuevoarchivo;
    private javax.swing.JButton jb_regresarcampos;
    private javax.swing.JDialog jd_Campos;
    private javax.swing.JDialog jd_Estandarizacion;
    private javax.swing.JDialog jd_Registro;
    private javax.swing.JMenu jm_archivo;
    private javax.swing.JMenuItem jm_campos;
    private javax.swing.JMenuItem jm_estandarizacion;
    private javax.swing.JMenu jm_guardar;
    private javax.swing.JMenuItem jm_registro;
    // End of variables declaration//GEN-END:variables
    private File archivo = null;
    private RandomAccessFile flujo = null;
    ArrayList<String> campos = new ArrayList();
    ArrayList<String> tiposcampos = new ArrayList();
    ArrayList<Integer> sizecampos = new ArrayList();
    ArrayList<Boolean> llaveunica = new ArrayList();
}
